const vertexShader=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uMvp;uniform mat4 uModel;varying vec3 vNormal;varying vec3 vPosition;void main(){vec4 p=uModel*vec4(aPosition,1.0);vPosition=p.xyz;vNormal=mat3(uModel)*aNormal;gl_Position=uMvp*vec4(aPosition,1.0);}`;
const fragmentShader=`precision highp float;varying vec3 vNormal;varying vec3 vPosition;uniform bool uWire;void main(){vec3 n=normalize(vNormal);vec3 light=normalize(vec3(.45,.7,.8));float diffuse=max(dot(n,light),0.0);float rim=pow(1.0-max(dot(n,normalize(-vPosition)),0.0),2.2);vec3 base=vec3(.48,.57,.57);vec3 brass=vec3(.85,.60,.22);vec3 color=base*(.24+diffuse*.72)+brass*rim*.24;gl_FragColor=vec4(color,1.0);}`;

function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
function program(gl){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vertexShader));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fragmentShader));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
function identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}
function multiply(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0])}
function rotation(x,y){const cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y);return new Float32Array([cy,sx*sy,-cx*sy,0,0,cx,sx,0,sy,-sx*cy,cx*cy,0,0,0,0,1])}
function translateZ(z){const m=identity();m[14]=z;return m}
function normals(v,idx){const n=new Float32Array(v.length);for(let i=0;i<idx.length;i+=3){const a=idx[i]*3,b=idx[i+1]*3,c=idx[i+2]*3,ab=[v[b]-v[a],v[b+1]-v[a+1],v[b+2]-v[a+2]],ac=[v[c]-v[a],v[c+1]-v[a+1],v[c+2]-v[a+2]],x=ab[1]*ac[2]-ab[2]*ac[1],y=ab[2]*ac[0]-ab[0]*ac[2],z=ab[0]*ac[1]-ab[1]*ac[0];for(const q of[a,b,c]){n[q]+=x;n[q+1]+=y;n[q+2]+=z}}for(let i=0;i<n.length;i+=3){const l=Math.hypot(n[i],n[i+1],n[i+2])||1;n[i]/=l;n[i+1]/=l;n[i+2]/=l}return n}

export class GearRenderer{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{antialias:true,alpha:true});if(!this.gl)throw new Error('浏览器不支持 WebGL');if(!this.gl.getExtension('OES_element_index_uint'))throw new Error('浏览器不支持 32 位网格索引');this.p=program(this.gl);this.rotationX=-.9;this.rotationY=.55;this.distance=3;this.radius=1;this.count=0;this.wire=false;this.bindControls();new ResizeObserver(()=>this.resize()).observe(canvas);this.resize();this.draw()}
  setMesh(vertices,indices){const gl=this.gl;this.vertices=vertices;this.indices=indices;this.count=indices.length;this.radius=0;for(let i=0;i<vertices.length;i+=3)this.radius=Math.max(this.radius,Math.hypot(vertices[i],vertices[i+1],vertices[i+2]));const ns=normals(vertices,indices);this.vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.vb);gl.bufferData(gl.ARRAY_BUFFER,vertices,gl.STATIC_DRAW);this.nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.nb);gl.bufferData(gl.ARRAY_BUFFER,ns,gl.STATIC_DRAW);this.ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,indices,gl.STATIC_DRAW);this.fit();this.draw()}
  fit(){this.distance=Math.max(this.radius*3.6,1);this.draw()}
  toggleWire(){this.wire=!this.wire;this.draw();return this.wire}
  resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,this.canvas.clientWidth*d),h=Math.max(1,this.canvas.clientHeight*d);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.draw()}}
  bindControls(){let drag=false,x=0,y=0;this.canvas.addEventListener('pointerdown',e=>{drag=true;x=e.clientX;y=e.clientY;this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(!drag)return;this.rotationY+=(e.clientX-x)*.008;this.rotationX=Math.max(-1.5,Math.min(1.5,this.rotationX+(e.clientY-y)*.008));x=e.clientX;y=e.clientY;this.draw()});this.canvas.addEventListener('pointerup',()=>drag=false);this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.distance*=Math.exp(e.deltaY*.001);this.distance=Math.max(this.radius*1.15,Math.min(this.radius*8,this.distance));this.draw()},{passive:false})}
  draw(){const gl=this.gl;if(!gl)return;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);if(!this.count)return;gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.useProgram(this.p);const model=rotation(this.rotationX,this.rotationY),view=translateZ(-this.distance),proj=perspective(.62,this.canvas.width/this.canvas.height,.1,Math.max(this.distance+this.radius*3,1000)),mvp=multiply(proj,multiply(view,model));gl.uniformMatrix4fv(gl.getUniformLocation(this.p,'uMvp'),false,mvp);gl.uniformMatrix4fv(gl.getUniformLocation(this.p,'uModel'),false,model);gl.uniform1i(gl.getUniformLocation(this.p,'uWire'),this.wire);for(const[name,buf]of[['aPosition',this.vb],['aNormal',this.nb]]){const loc=gl.getAttribLocation(this.p,name);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0)}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.ib);if(this.wire){gl.disable(gl.CULL_FACE);gl.drawElements(gl.LINES,this.count,gl.UNSIGNED_INT,0)}else gl.drawElements(gl.TRIANGLES,this.count,gl.UNSIGNED_INT,0)}
}
